### ISSUE TITLE
audio upload playback does not seek

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#102]
The upload audio playback does not seek to position properly and also because of broken seeking cannot remember position after pause.

**Comment by cavis** [comment]
Was able to reproduce this by playing back a long-ish piece of audio, and seeking towards the end (past the amount buffered).  Tried preventing seeking past the "percent buffered", but that didn't consistently solve the issue either.

At this point, I think we should abstract the player service back 1 level, and only use aurora if the file isn't playable via native playback.  We need to keep aurora anyways for validations, and this keeps the code around until we start allowing mp2 uploads.
