### ISSUE TITLE
Feed story ordering

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#124]
Somewhere in Publish, show the order of the stories as they will appear in the feed. Maybe a tab on series-edit?

**Comment by sandikbarr** [comment]
Seems like we also want a sort by feed order on the search page

**Comment by cavis** [comment]
Sorting by "published_at" will give you the order of the feed-items.  Though it's a bit confusing, as I don't think we display the published date anywhere in the "card" UI.

I was thinking of this as a tab on the Series page, which just fetched all the Stories in that Series, and gave you a real simple list of them ordered by published-at.  (The order of the items in your feed).  Make sense?

Or maybe this is entirely useless.

**Comment by sandikbarr** [comment]
That makes sense, yeah 👍

**Comment by sandikbarr** [comment]
Stories will have both a public/private flag as well as a publishedAt date. The tab should represent all stories within a series. Stories without a publishedAt date will be at the top of the sorted list. Stories that do have a publishedAt date but are not in the public feed (ones that are private or with publishedAt dates in the future) should have some indicator in the UI to represent their status, 
maybe a different background color or something.
