### ISSUE TITLE
Should validate image file type

### ISSUE THREAD

**Issue by gcampo88** [PRX/publish.prx.org#136]
Should constrain image file types to jpg and png both by limiting the file selection to image mime types, and show a file type-specific error message when unacceptable file type is chosen

**Comment by sandikbarr** [comment]
Now that I've looked up the iTunes image requirements multiple times and it's staring me in the face, it bugs me a little bit that the image size, i.e. 1400x1400 doesn't have any spaces in it. If it doesn't bug anyone else, it's probably fine. But if you want to adjust it while working on the mime type validation, that's definitely cool with me. 😃
