### ISSUE TITLE
Publish button handling

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#154]
Since we call things "public" and "private" on the dashboard, we should rethink the current publish/unpublish buttons on the story page.

Questions to answer:

- Keep setting it "above the fold"?  (Meaning it's a button/action rather than a localStorage-able state on the Story resource).  Or just make it an element on the form?
- How does this play with explicitly setting the `published_at` date to influence your podcast item ordering?

I was leaning more towards keeping this an action/button, with a bootstrap-style [button dropdown](http://getbootstrap.com/components/#btn-dropdowns).  This could allow you to alter it as a boolean, or explicitly set the date.  And calling it out above-the-fold prevents users from having unsaved-changes to the public/private state.

**Comment by sandikbarr** [comment]
Related to #166

**Comment by cavis** [comment]
I'm calling this a duplicate of #166, since this will be solved there.
