### ISSUE TITLE
Series, Podcast Distribution, Vanity path changes

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#165]
- [x] Move the field up to the top with "PRX Feeds", as it affects those feed urls
- [ ] Explain in the hint how it is used instead of the id # in the PRX Feed urls
- [x] Make the text field much shorter, as this field should be only a 5-20 characters, like the feedburner feed path

**Comment by sandikbarr** [comment]
For the hint, not sure how users would refer to or understand the vanity path.

Does an input like this make sense at all?
![feedburner45](https://cloud.githubusercontent.com/assets/2250413/21430509/12ec2d54-c829-11e6-914f-85b6a761ae7f.jpg)

**Comment by gcampo88** [comment]
@sandikbarr I think that would make it much clearer! Also noticed just now that the Published Feed url doesn't update once you save your new Vanity/Custom Path -- only shows up in place once you refresh the page. Made a new issue for it --#176

**Comment by kookster** [comment]
I read these in the wrong order, yes, that is helpful, and is the part you
can update, though it is in the middle not the end. (It is also used to
customize where the related files are saved, not just the rss xml resource.)

We also need sort of the reverse field, where you can set the prefix for
the audio files (e.g. podtrac and blubrry), I'll open a ticket.
