### ISSUE TITLE
Series, Podcast Distribution, author info

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#167]
Show the author info that will be published for the podcast based on the account
Allow the user to override this information and set the author full name and email.

**Comment by gcampo88** [comment]
based on [the example of 99pi](https://feeder.prx.org/api/v1/podcasts/23), looks like we currently only give full name for `author`, and skip the email (`owner` has both name and email): `"owner": {
    "name": "Roman Mars",
    "email": "roman@prx.org"
  },
  "author": {
    "name": "Roman Mars"
  },`

So, assume we should just allow user to override author name?

**Comment by cavis** [comment]
Updated requirements: Author-name is required, Author-email is optional.  So still need to add an Email field.

(Given how this form is getting fairly long, may want to consider having these 2 fields on a single line, under a single form label... but I'll leave that up to you!)
