### ISSUE TITLE
Story, Podcast Distribution fields

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#168]
- [ ] Show and make overridable the GUID - overwrite by writing to `feeder.episode.original_guid`
- [ ] Show and make overridable the author, name and email, starting with podcast author, which defaults to prx user
- [ ] Show the enclosure url, not editable

**Comment by sandikbarr** [comment]
Sandi Barr [10:07 AM]  
My assumption on these two https://github.com/PRX/publish.prx.org/issues/168 and https://github.com/PRX/publish.prx.org/issues/167 is that they've got feeder dependencies. LMK if I'm incorrect and those are ready to be worked.
Ryan Cavis [10:26 AM]  
there’s probably one TODO there to make CMS send the “defaults” to Feeder
but i think you should be able to get/set that data from feeder
the current FeederPodcastModel is just getting/putting to the podcasts endpoint
https://feeder.prx.org/api/v1/podcasts/23
you can see in roman’s setup, many more of the fields are there than in a brand-new-podcast you create
but you should be able to send those fields with your new Podcast
Andrew Kuklewicz [10:29 AM]  
you can do both #167 and #168, they use fields that are in feeder, but are already available in the feeder api
the main thing that is missing is for the author (not the guid or enclosure url), which is to make sure once overridden in feeder
it doesn't get rewritten by an update from cms, which currently sends all its updates via asynch messages
to update related feeder entries
but, you can do all the publish work for 167 and 168 w/o that override tracking being in place
Ryan Cavis [10:31 AM]  
ah, right
Andrew Kuklewicz [10:32 AM]  
we also should send more of the defaults to feeder on story create
but that also is behind the scenes, won't affect how these fields are made editable on publish
just how soon a default value shows up in them, either immediately, or after the asynch pudate

**Comment by sandikbarr** [comment]
Related: https://github.com/PRX/feeder.prx.org/issues/161

**Comment by sandikbarr** [comment]
How should I get the episode by prx story from feeder? Do we need to add a story or prxUri filter_param or is there support for this already that I'm just not seeing?
