### ISSUE TITLE
Story, Embeddable player staging host

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#169]
Use `play-staging.prx.tech` url on `publish-staging.prx.tech`

**Comment by cavis** [comment]
@gcampo88 updated reqs: to get this also working in prod, we should add a `PLAY_HOST` to `env-example`.  Can default that to play-staging, since we tend to use the staging env for dev.

Will also need to update the staging and production ECS task definitions, to correctly set this config.
