### ISSUE TITLE
Series, Podcast Distribution, subscribe URL for embed

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#171]
The `us` value passed into the embed player is the subscription link for the podcast, so the best place to get this is on the podcast distribution tab for the series.

On Series, Podcast Distribution, along with the site url ask for a subscription link.

I think this is something we can save either in feeder (as it is podcast related), or in the `cms.series.distribution` for this podcast, discuss which is a better place - it is not needed by feeder per se, so I am tempted to save as part of `cms.series.distribution`

In a later enhancement, we will need a more sophisticated subscribe UI, probably an overlay with options including RP and other common apps for the current client platform.

**Comment by kookster** [comment]
Also worth noting - the `pcast:// scheme in front of an rss feed url will launch the default podcast player on various os.

It is supposed to work on iOS, macos, modern windows, and android - I tested all but android.

There are app specific schemes as well, but perhaps we support pcast and radiopublic to start.

Here's a whole project dedicated to doing subscribe buttons:
https://github.com/podlove/podlove-subscribe-button

**Comment by gcampo88** [comment]
The player that you create on Publish now operates based on RSS feed + GUID combo, no longer uses the passed-in params. (The only time it uses passed-in params is for a Story in a Series without a podcast distribution, in which cases it uses the beta link). So the subscription URL comes from the RSS feed, no need for us to find it or pass it in. Lots of additional subscription options available now too with the overlay on pause as of RP additions recently. Going to close this!
