### ISSUE TITLE
Story, Embeddable Player, image and audio tags

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#172]
When a story is an episode of a podcast, both the image and audio urls should really come from the podcast image and enclosure audio, so the best place to get these values is feeder.

Since in publish this is the only case we are currently supporting I would use those - I'll add another ticket to track the other possibilities.

**Comment by gcampo88** [comment]
this is what we have in there now: 
```
    if (this.story.images.length > 0) {
      let img = this.story.images.find(img => !img.isDestroy);
      if (img) { this.imageUrl = img.enclosureHref; }
    }
    
    if (this.story.versions.length > 0) {
      let firstAudio = this.story.versions[0].files.find(file => !file.isDestroy);
      if (firstAudio) { this.audioUrl = firstAudio.enclosureHref; }
    }
```
do we want something like this? 
```
if (this.story.doc.has('prx:series')) {
      this.story.doc.follow('prx:series').subscribe(seriesDoc => {
        this.subscriptionUrl = window['ENV'].CMS_HOST + seriesDoc['_links'].self.href;
      });
    }
    if (this.story.doc.has('prx:audio')) {
      this.story.doc.followItems('prx:audio').subscribe(audioDoc => {
        this.audioUrl = window['ENV'].CMS_HOST + audioDoc[0]['_links'].enclosure.href;
      });
    }

    if (this.story.doc.has('prx:image')) {
      this.story.doc.follow('prx:image').subscribe(imageDoc => {
        this.imageUrl = window['ENV'].CMS_HOST + imageDoc['_links']['enclosure'].href;
      });
    }
```
is there a less clunky way I'm overlooking?

**Comment by cavis** [comment]
I think you're going to want to look more at what the series-podcasts tab is doing.  When the tab is `ngOnInit`'d, load the distribution, and follow the link to feeder.

But I'm not seeing any way to get a link from the CMS-story to the Feeder-episode.  Looking into it...

**Comment by gcampo88** [comment]
per slack, holding off on this for now: 

Andrew Kuklewicz [11:28 AM]  
I remember we talked about having the story distro and feeder episode created automatically if the story was in a series with an associated podcast distro

[11:29]  
I don't think it does that atm

Ryan Cavis [11:29 AM]  
Ah, okay.  In that case, this publish ticket is likely blocked until then

**Comment by gcampo88** [comment]
currently trying ugly stuff like this in `player.component.ts`
```javascript
  loadStoryDistribution(story: StoryModel) {
    story.loadRelated('distributions', true).subscribe(() => {
      this.storyDistribution = story.distributions.find(d => d.kind === 'episode');
      if (this.storyDistribution) {
        this.storyDistribution
            .doc
            .followLink({href: this.storyDistribution.url})
            .subscribe(feed => {
              // getting console errors about http/https disagreement; audio won't play
              this.audioUrl = feed['media'].filter(m => m.type === 'audio/mpeg')[0].href;
              // this.imageUrl == where is it in result from feeder?
            });
      }
    });
  }
```
not sure if I'm approaching this the right way -- or whether I should just hold off in light of ongoing stuff over in play.prx.org ?

**Comment by kookster** [comment]
@cavis now that we are using the feed url / guid for the embed, can we close this?

**Comment by kookster** [comment]
obsolete
