### ISSUE TITLE
Search, stories, remove link to series from story card

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#174]
![image](https://cloud.githubusercontent.com/assets/46439/21409655/66c6888c-c7a9-11e6-859b-47eeab981d6f.png)

Retain the series title under the story title, but don't make it a link.
If folks need to get to the series, then we have a few options.
One is to go to the story, then get to the series from there.
Second is they change to `series` search and get the series there.
![image](https://cloud.githubusercontent.com/assets/46439/21409712/b6ad3e5e-c7a9-11e6-9d78-d66b3a3fa542.png)

**Comment by sandikbarr** [comment]
Needing to make changes to this line for multiline text truncation, so this will be in the same PR.
