### ISSUE TITLE
Published Feed doesn't update to include custom/vanity path at first

### ISSUE THREAD

**Issue by gcampo88** [PRX/publish.prx.org#176]
Published Feed doesn't update to include your new custom/vanity path when you hit "save" -- only shows up once you refresh the page. could be solved by @sandikbarr 's suggestion of having input field for custom path be a part of the Published Feed input field (see #165)

**Comment by sandikbarr** [comment]
This explains why the field wasn't making sense to me!

**Comment by kookster** [comment]
I didn't see @sandikbarr's suggestion, but you can't edit the published url
except for the vanity path.
It is supposed to be there for display purposes, like the embed url, so you
can either use it, or submit it to feedburner.

There is a different field (I think in another ticket), related to the
embed player, to edit and manage a public url for the feed which is usually
a feedburner feed url.
