### ISSUE TITLE
Draft audio version removed from local storage

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#194]
When an audio version on a story has had the explicit value overridden to either Explicit or Clean from the value on the series template, if the user sets the explicit value to none/empty string, a draft is saved in localStorage with "changes" showing on the story page. However, when navigating back to the dashboard, that draft is removed from localStorage. If Explicit or Clean is the "changed" value, the draft remains in localStorage and is shown on the dashboard as such.

**Comment by kookster** [comment]
@sandikbarr did #182 fix this?

**Comment by sandikbarr** [comment]
No, #182 had this problem, but it was a separate issue that the dashboard was removing the draft, so I opened this ticket. However this will no longer be a problem with forcing Save or Discard with #282. So let's close it!
