### ISSUE TITLE
Podcast, list of episodes table styles

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#196]
![image](https://cloud.githubusercontent.com/assets/46439/21811457/bcd5a6e4-d71d-11e6-8e8e-e59eaa9bfdca.png)

I think we should do a UI review of this tab.
Seems like it could look more like a table, or rows of data.

**Comment by sandikbarr** [comment]
Kind of rough... I'm thinking accordions for each section with relevant links below the tabs
<img width="733" alt="screen shot 2017-01-12 at 8 27 08 pm" src="https://cloud.githubusercontent.com/assets/2250413/21916505/bbfe1ef0-d906-11e6-8b34-c4213b7381e6.png">
