### ISSUE TITLE
Long hero title pushes content below toolbar when scrolled

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#199]
A story title longer than one line will push the info content (last saved) below the toolbar when the page is scrolled. We may want to limit to one line of the title displayed on scroll or something.
<img width="711" alt="screen shot 2017-01-10 at 5 56 56 pm" src="https://cloud.githubusercontent.com/assets/2250413/21829825/45b7725e-d75e-11e6-822f-6763ecc68b74.png">

**Comment by kookster** [comment]
Let's make it a single line which can have an ellipsis for the end
