### ISSUE TITLE
Unclickable labels covering up clickable links

### ISSUE THREAD

**Issue by gcampo88** [PRX/publish.prx.org#202]
This is happening in a couple places. 
On the Home page:
- status label on individual story cards renders that portion of the story card unclickable
- hover tip over "Your Standalone Stories" completely covers the "View all X" link to the search page

Audio Templates page for Series:
A blank hover-tip is covering up much of the clickable area for the Minimum and Maximum length durations on the Series Audio Templates page. (Actually, looks like the hover-tip, whether blank or with text, is covering up clickable items in several places in the app-- particularly inline input fields like these min and max fields)

**Comment by sandikbarr** [comment]
Hover tip removed. Closing.
