### ISSUE TITLE
Series, Templates, fill out min max time in H:M:S not just total seconds

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#237]
I don't think most people have handy the duration in seconds, so would be easier to do this in minutes, but seconds would be tough.

"Thought the min and max on the audio template was for minutes not seconds"

**Comment by cavis** [comment]
Went with an HH:MM:SS series of 3 tiny number inputs.  Actually works pretty well, since I can roll over values > 60 into the next higher field using angular magic.
