### ISSUE TITLE
Series, Podcast distribution, homepage url scheme required is confusing

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#241]
On homepage url, need to tell people it needs "http", most people won't know to do that.

Instead handle it being missing, add hints/docs and error message that include this, or find other way to ask this (scheme select).

**Comment by sandikbarr** [comment]
When adding a link in the markdown editor, if http:// or https:// is not provided, it prepends http://. However we handle it, we should make these url fields behave consistently.

**Comment by kookster** [comment]
do the magic!

**Comment by sandikbarr** [comment]
Too quick on the draw. If I start typing ht, I get "http://ht"
