### ISSUE TITLE
fix component tests

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#25]
In RC5, `overrideComponent` doesn't quite work right - it doesn't actually mock out the dependencies/constructors/bindings of the component.  When RC6 hits, this should be resolved.  Should go back and try to fix the component tests.

**Comment by cavis** [comment]
Also need to backfill some tests for #38 ...

- [ ] `series/series.component.spec.ts`
- [ ] `shared/form/button.component.spec.ts`
- [ ] `shared/hero/hero.component.spec.ts`

**Comment by cavis** [comment]
That overrideComponent issue _appears_ to be fixed in RC6.  But would prefer to upgrade when `angular-cli` hits RC6 as well.  (And I've been seeing some other webpack-y issues with karma that will hopefully get sorted out)

**Comment by kookster** [comment]
I think you are doing this @cavis as part of the upgrade to ng v2

**Comment by cavis** [comment]
It may end up being a separate PR ... but yes.
