### ISSUE TITLE
Story, editing the full description, need more of a hint

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#250]
More guidance on how long a full description should be? I don't know if iTunes has guidance, I don't want more than 3 sentences.

Also tailor the initial box size to match this hint and expectation of how long it should be.

(I'll also add, it may not be clear to users that they can add images or what formatting it allowed, so some specific help link for editing here could be useful.)

**Comment by gcampo88** [comment]
per Podcast Connect, can't be more than 4000 characters (I'll add that as an upper limit to the length validation). No other guidance from iTunes
