### ISSUE TITLE
Navigating w/o saving and locally saved changes confusing

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#253]
Unsaved changes - that last sentence, I'm not sure what that means, stored in my browser? but how do I get back there?

Why would I want to not save my changes? Can't see why I wouldn't want to do that. Never something I wanted to do - I save or I don't.

To me draft means I haven't published yet.
(Seems like "draft" should only happen we have an unsaved doc we rescued from being lost, and we can come up with a different name for that)

**Comment by sandikbarr** [comment]
The user will have to either Save or Discard their changes before navigating away. (Rules for allowing saving of incomplete stories will be adjusted with #275). The modal will have two buttons, Okay and Cancel. Cancel closes the modal and allows the user to review the changes made and either Save or Discard. Okay will discard changes and continue navigation.
