### ISSUE TITLE
Series, Podcast distribution, removing template

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#257]
Doesn't highlight when it is selected by tabbing - remove from tab order
Clicking/return on Delete link for remove template doesn't prompt

**Comment by gcampo88** [comment]
I think we decided in conversation that taking the remove buttons out of the tab index (and thus largely removing the odds that someone will press them by accident) was enough, so that's what I'm doing. If we also want this to open up the confirmation modal we can reopen this. Ca va?
