### ISSUE TITLE
itunes:explicit set to 'explicit' - is that the right value?

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#260]

**Comment by sandikbarr** [comment]
Series is using "explicit" and episodes is using "yes" (except maybe where we are defaulting the story to the series explicit value, which we decided is redundant.) According to https://help.apple.com/itc/podcasts_connect/#/itcb54353390 yes, explicit, or true are valid values.

**Comment by kookster** [comment]
I looked at the code, and seems like we are using explicit and clean - which is good and fine.

The V3 audio_versions.explicit is either `clean` or `yes`, so at some point that should get rationalized,bot not in this ticket.
