### ISSUE TITLE
Related field validations (min & max seconds) triggering before editing complete

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#266]
After editing min, get an error about it being greater than max, before max has even been edited.
Not sure how to solve this - delay on the validation until after max has lost focus or 30 seconds later, whichever comes first? Or just have it when min loses focus instead of on changing the value?
Or we could also do nothing - this is not so bad on its own, but I think was exacerbated by the general difficulty of editing the min and max fields. We could just fix that editing in general, and leave the validations as is for the next round of testing.

"Why is it chiding me about the min being less than max when max isn't set yet?"

**Comment by cavis** [comment]
Decided to make the max fields "chase" the min.  So if you set min >= max, it sets `max = min + 60`.  This way, you never get a validation error while setting the min, which usually happens first.

You can still get a validation error by explicitly setting the max < min.
