### ISSUE TITLE
Link to add a story from Series > Episode In Series view

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#267]
Thought going to "0 Stories in a Series" would lead to a way to make a new story.

**Comment by sandikbarr** [comment]
Thinking I would prefer having an Add Story link on the series and disable the 0 Stories in a Series when 0. The Add Story link would give a better workflow to first time users setting up their series.

**Comment by gcampo88** [comment]
Note that currently, the only way to get to a New Story page through the UI is from the [+] square on the home dashboard. If the series you want isn't in the top / most-recently-edited 10, no way to get to that new story in series page for it.
