### ISSUE TITLE
dropdown select component

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#283]
@sandikbarr commented on [Mon Oct 17 2016](https://github.com/PRX/meta.prx.org/issues/15)

A dropdown select component is needed that supports placeholders, clearing the selection, and ideally multiple selections.

At this time, the most popular option [ng2-select](https://github.com/valor-software/ng2-select) requires including bootstrap's dropdown CSS separately. There is a [PR](https://github.com/valor-software/ng2-select/pull/375) to remove bootstrap dependencies. We may have to create and maintain our own CSS with this approach, but hopefully we could find a starting point from other users, seems like it would be less of a headache after ng2-select is more stablized.

Other prebuilt options include [ng2-select2](https://www.npmjs.com/package/ng2-select2) and [angular2-select](https://www.npmjs.com/package/angular2-select) which are much less popular.

**Comment by sandikbarr** [comment]
Tried out [angular2-select](https://basvandenberg.github.io/angular2-select/) today with chart.prx.org options. Seemed to work fine, no problems. chart.prx.org is on latest angular & cli. Would suit our needs for times when we want to be able to clear the selection or select multiple options (like search.)

**Comment by cavis** [comment]
Initial implementation in PRX/styleguide.prx.org#55, version `0.0.16`.  Still many TODOs, but will address those in subsequent tickets.

Added to publish with #456 - so should review/close this along with that one.  Just to add yet another ticket to that PR.

**Comment by cavis** [comment]
Deploy'd!
