### ISSUE TITLE
Unsaved changes, consider 'Discard Changes' as button text

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#325]

**Comment by sandikbarr** [comment]
"Discard Changes" is far too big here. All of our other buttons are one word. Going with "Discard"
<img width="501" alt="screen shot 2017-02-02 at 1 20 03 pm" src="https://cloud.githubusercontent.com/assets/2250413/22564502/6399d4ee-e94a-11e6-8739-af369dbabd99.png">

As far as implementation is concerned, I could make a case for having the first button in the modal always being the primary button or to add a primary button indicator to the ModalState. The callback setup based on hard coded button labels is a little funky.
