### ISSUE TITLE
Investigate explicit value overrides in episode vs. podcast 

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#337]
I believe this is what we decided to do in this milestone instead of going ahead and moving story explicit  value, as a bit more info to decide how often we see individual episodes vary from the series.

To do this, we could check the existing radiotopia and moth podcasts in itunes and check how much variance exists.

**Comment by gcampo88** [comment]
I checked out the feeds for a bunch of Radiotopia podcasts, and it looks like people _do_ frequently set a different value for `explicit` on an episode than exists on the parent podcast. (It also looks like Radiotopia producers also redundantly set the episode `explicit` value to the same value as already exists on the podcast quite frequently.) 
<hr>
A random assortment: 
**99PI:** 
channel: clean
episodes: 64 clean, 188 no, 1 yes

**The Moth**
channel: clean
episodes: 6 clean, 15 yes, 1 no

**Radio Diaries**
channel: clean
episodes: 5 clean, 3 yes

**The Heart**
channel: yes
episodes: 38 yes, 35 no

**Allusionist**
channel: clean
episodes: 49 clean, 1 yes

**The Bugle:**
channel: yes
episodes: all yes

**Kitchen Sisters Fugitive Waves:**
channel: clean
episodes: no designation on any, so all inherit "clean"

**Mortified**
channel: yes
episodes: all yes

**Millenial:**
channel: clean
episodes: only one has designation (yes) -- all others have no designation so inherit "clean" 

<hr>

Given the fact that it's very common to override the podcast `explicit`value for an episode, I vote we keep our current setup, which is clear in the hint language that there's no need to set the value if it's the same as the parent, and which is also very easy to find for someone who does want to override that value.

**Comment by kookster** [comment]
very helpful. I agree on keeping the language for sure.
So here's the question - do we think changing this is common enough that we should set it in the basic info instead of having to go to the podcast distribution tab?

**Comment by gcampo88** [comment]
My vote would be to leave it where it is. Reasons: 
a) it is podcast-specific information, after all
b) leaving it there might cut down on people redundantly setting it to what the parent is (the basic info tab is already long enough that I suspect hint text won't help much there).

But I don't feel strongly. Should we ask G what she thinks?

**Comment by kookster** [comment]
all compelling reasons - yeah, the "let's ask more people before we spend time making changes" is a good thought.
