### ISSUE TITLE
series, podcast distribution unable to clear author email

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#343]
The series podcast distribution author email field cannot be cleared after it has been set. As this is not a required field, empty string should be allowed.

**Comment by kookster** [comment]
The reason we made author email required was b/c we were using it for the owner values (I believe), as itunes need an owner to be able to claim a feed, and author is optional in rss.

Now that we have owner, we should probably change the validation, and shift it to owner - I'll take a look.

**Comment by sandikbarr** [comment]
If it's required, the UI isn't giving appropriate feedback. Empty string is falsey, so it just isn't getting set in encode.

**Comment by kookster** [comment]
oh I misread that as the issue was it needs to be required - my bad.

**Comment by sandikbarr** [comment]
Not sure about required, but this is where the issue is FeederPodcastModel::encode()
`
if (this.authorName || this.authorEmail) {
      data.author = {
        name: this.authorName,
        email: this.authorEmail
       };
    }
`

Similar logic is being used in your new branch: https://github.com/PRX/publish.prx.org/pull/386/files#diff-783b8bbbc6d0c57c8a4950742293cf9eR120
