### ISSUE TITLE
upgrade to angular 2 final

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#35]
- [x] Upgrade dependencies
- [x] Get off the now-entirely-deprecated forms module

**Comment by cavis** [comment]
For dependencies, something like this:

![image](https://cloud.githubusercontent.com/assets/1410587/18283002/9bce92cc-7420-11e6-8adf-374026802f79.png)

Though when `angular-cli` updates, that may be the easier option.

**Comment by kookster** [comment]
merged.
