### ISSUE TITLE
Filter v3 series out of v4 requests

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#356]
CMS already has a v4 filter for series, and I see tests that show it prevents v3 series from being returned.

If v3 series are showing up in the UI, I suspect it is because publish is not using the filter to request only v4 series.

**Comment by sandikbarr** [comment]
Is this ticket about this story showing up in search? It is a v4 story, but the series is v3, bad data. There is a v4 filter on the stories request. Are we wanting any stories with a v3 series filtered out of search?
<img width="347" alt="screen shot 2017-02-07 at 8 35 33 am" src="https://cloud.githubusercontent.com/assets/2250413/22695460/780ff31c-ed10-11e6-8c9a-3333bc7c3634.png">

**Comment by kookster** [comment]
I am probably not remembering right, but I thought it was for the series
itself showing up, but maybe it is this - bad data.

**Comment by sandikbarr** [comment]
When this came up in testing, it was confusing that we couldn't find the series in search.

**Comment by sandikbarr** [comment]
Removing the offending bad data and closing.
Bye, Felicia
<img width="1180" alt="screen shot 2017-02-08 at 3 30 11 pm" src="https://cloud.githubusercontent.com/assets/2250413/22758289/ad352cde-ee13-11e6-8fad-daf9709b0697.png">
