### ISSUE TITLE
timepicker doesn't know about daylight/savings time zones

### ISSUE THREAD

**Issue by gcampo88** [PRX/publish.prx.org#360]
posting on behalf of @farski, who pointed out: the timepicker does not alter the time zone extension in accordance to daylight/savings time. (e.g.: if I set a release date for an episode in February, it should be HH:MM EST, but if I set a release date for July, it should be HH:MM EDT)

**Comment by sandikbarr** [comment]
This bug is fixed in the new timepicker in the styleguide and could be fixed by using the styleguide timepicker component for the release date, which would then make the Publish timepicker obsolete.
