### ISSUE TITLE
Set podcast-dist owner

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#372]
We're already setting a name/email for podcast distribution author.

Add 2 more fields underneath the series-podcast-distribution "Author Information".

- [ ] Title: Owner Information
- [ ] Hint: something relating to https://help.apple.com/itc/podcasts_connect/#/itcb54353390
- [ ] Would be great if it duplicated the Author fields the first time you filled them out.  (Keep them in sync until the user manually changes the owner to be something different).

**Comment by cavis** [comment]
Hold on this for now - PRX/feeder.prx.org#211 is good enough in the short term.

**Comment by kookster** [comment]
#386 includes setting owner, author, and managing editor

**Comment by pkarman** [comment]
@cavis @kookster can this be closed?

**Comment by cavis** [comment]
Yeah, this is now defunct.
