### ISSUE TITLE
Set the episode summary

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#378]
Currently we use the html description in both the <description> tag and the <itunes:summary> tag, with the summary stripped of all but anchor tags.

Some folks still like to edit this themselves, so we could offer that as an option on the `podcast episode info` tab.

Could that be a stripped down prosemirror editor with only links available as formatting?

**Comment by sandikbarr** [comment]
Both episode and series podcast info will have a new summary field.
- [ ] summary is to be a prosemirror field allowing only links with a 4000 char limit
- [ ] docs to describe how feeder falls back on desc when this optional summary is not filled out
- [ ] preview available after save of what the summary will look like if it was not entered by the user
