### ISSUE TITLE
wysiwyg "changed" when gets focus but not actually changed

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#379]
The wysiwyg editor is showing the orange "changed" outline when it has focus but no text has been changed. To reproduce, go to a story page, click the description field but do nothing else. You will be prompted to Discard changes before navigating away.

![image](https://cloud.githubusercontent.com/assets/2250413/23801456/d741e4ee-0575-11e7-90ec-b19127b63cd6.png)

**Comment by kookster** [comment]
With latest fixes, I don't see this anymore.

**Comment by sandikbarr** [comment]
yep, Ryan's updates to no longer save/reset editor fixed this
