### ISSUE TITLE
Uncaught QuotaExceededError

### ISSUE THREAD

**Issue by debenedictis** [PRX/publish.prx.org#408]
I went to the Ear Hustle series (https://publish.prx.org/series/37771/podcast) Podcast Info tab and tried to change the "Enclosure Prefix Url" from:

    http://dts.podtrac.com/redirect.mp3/

to:

    https://dts.podtrac.com/redirect.mp3/

As soon as a typed the 's' after http I got 'Uncaught QuotaExceededError' 'The quota has been exceeded.'  Along with this the log listed below.

Nonethless, the PRX Publishing Platform allowed me to make the change to https.

----log----
setItem@[native code]
store@https://publish.prx.org/main.2ba537cd1075fc1f5f1f.bundle.js:1:494981
set@https://publish.prx.org/main.2ba537cd1075fc1f5f1f.bundle.js:1:491143
doOnChange@https://publish.prx.org/main.2ba537cd1075fc1f5f1f.bundle.js:1:145296
https://publish.prx.org/main.2ba537cd1075fc1f5f1f.bundle.js:1:78611
https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:232:3303
https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:316:5225
__tryOrUnsub@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:681:558693
next@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:681:557979
_next@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:681:557025
next@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:681:556697
next@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:405:115292
emit@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:316:4694
viewToModelUpdate@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:554:1394
https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:498:376
_handleInput@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:505:845
https://publish.prx.org/main.2ba537cd1075fc1f5f1f.bundle.js:1:78240
https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:218:2365
https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:625:828
onInvokeTask@https://publish.prx.org/vendor.15af82963aee76045fde.bundle.js:316:8020
runTask@https://publish.prx.org/polyfills.e64f3f32721ac31444b3.bundle.js:36:3206
invoke@https://publish.prx.org/polyfills.e64f3f32721ac31444b3.bundle.js:36:9004

**Comment by cavis** [comment]
What browser were you using?

At first glance, this appears to be us exceeding some browser-specific limits on localstorage size.  Which I also find odd, since we only use localstorage to hold series/episode state until you click save/discard.  (And we force you to save/discard before leaving the page).  I'll take a look to see what might be stacking up in there over time.

**Comment by debenedictis** [comment]
I was using Safari.

**Comment by cavis** [comment]
Were you by chance in private browsing mode?

**Comment by debenedictis** [comment]
I do not believe that I was in private browsing mode.

**Comment by cavis** [comment]
Update: pretty sure this is related to Safari security settings (ad blockers, plugins, etc).  And not us getting anywhere near the 5mb limit for localstorage.

This can be replicated pretty easily by putting safari in private-browsing mode.  The TODO here is to:

1. Actually check if localstorage works (something [like this](https://stackoverflow.com/a/27081419) perhaps?  or maybe there's a better solution out there)
2. If not enabled, gracefully allow the user to keep using Publish if possible.  I'm not sure all the implications of pretending localstorage isn't there.  If this won't work, throw up a warning modal to the user telling them how to fix the issue.

**Comment by debenedictis** [comment]
@cavis Did you want me to test this again?

**Comment by cavis** [comment]
Nah, I think I have all the info I need.  Should have a fix in the next day or two, then I'll ping you to re-test.

**Comment by cavis** [comment]
@debenedictis can you confirm that you can't get this error in prod anymore?  (It's actually been deployed for awhile now).

**Comment by debenedictis** [comment]
I have confirmed that I no longer get the error.  Thank you.
