### ISSUE TITLE
Sidedoor Published Episode (scheduled) Not In Feed

### ISSUE THREAD

**Issue by debenedictis** [PRX/publish.prx.org#414]
Gabe at Sidedoor reported that a published episode is missing.
The published episode is here:
    https://publish.prx.org/story/207050

The feed is here:
    https://f.prxu.org/sidedoor/feed-rss.xml

http://castfeedvalidator.com/?url=http://f.prxu.org/sidedoor/feed-rss.xml

<img width="506" alt="screen shot 2017-06-07 at 9 47 05 am" src="https://user-images.githubusercontent.com/588861/26881941-ee30d106-4b66-11e7-800d-847e75c064bb.png">

**Comment by kookster** [comment]
resolved, and we fixed the waiting episode publish in feeder
