### ISSUE TITLE
channel pubDate older than item pubDate

### ISSUE THREAD

**Issue by debenedictis** [PRX/publish.prx.org#430]
Stitcher only updates based on the _feed_ pubdate, not the pubdate of the most recent episode.  Therefore Stitcher is not picking up the latest episode, for example, in http://f.prxu.org/sidedoor/feed-rss.xml.

**Comment by gcampo88** [comment]
supporting links: 

https://feeder.prx.org/api/v1/podcasts/69/ podcast -> `publishedAt: "2017-07-12T04:00:00.000Z"`
https://feeder.prx.org/api/v1/podcasts/69/episodes latest ep-> `publishedAt: "2017-07-19T04:00:00.000Z"` (a week after the publishedAt for podcast)

could be a feeder issue...

**Comment by gcampo88** [comment]
most likely solved with https://github.com/PRX/feeder.prx.org/pull/250. moving this to 'done' and will close when confirmed.

**Comment by gcampo88** [comment]
no issues like this in 6 weeks; closing!
