### ISSUE TITLE
Publish button should change when scheduling

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#437]
When an episode release is configured to be scheduled, currently you have to hit a **Publish** button to schedule it. This is inconsistent with much of the UI, where a scheduled episode has a status of SCHEDULED, and appears in a Scheduled list, separate from the Published list. It seems like maybe that button should change to **Schedule** or **Schedule Release** or something when there is a future release date.

**Comment by cavis** [comment]
Yeah, I've heard this complaint from users a couple times now.

**Comment by amardavich** [comment]
You could show the scheduled date and time above the publish button or have it say "Schedule to publish on" if you have scheduled something. It would put you a little more at ease to hit "publish."

**Comment by farski** [comment]
Got another report of an episode not being released when it was supposed to because of the confusion this causes

**Comment by brandonhundt** [comment]
@IcusFMagni Recommend closing this in favor of #579
