### ISSUE TITLE
Audio file updates are failing when two files updated concurrently

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#440]
The validation for consistent format will fail if one more than one file is validated at the same time.
Consider row level locking the audio file before updating the status.

**Comment by kookster** [comment]
https://github.com/PRX/prx.org/pull/232

**Comment by gcampo88** [comment]
should be taken care of by the locking in https://github.com/PRX/cms.prx.org/pull/328

**Comment by kookster** [comment]
closing since this is now deployed, and not occurring since.
