### ISSUE TITLE
Episode titles are clipped on edit page

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#442]
When pegged to the top of the screen, descenders are clipped 

<img width="124" alt="screen shot 2017-08-22 at 11 06 53 am" src="https://user-images.githubusercontent.com/3483/29572329-03dd9de6-872a-11e7-88d3-f92d2871bfcb.png">

**Comment by gcampo88** [comment]
also happening in Spot use of prx-hero

**Comment by rpeterman-gp** [comment]
Issue moved to [PRX/styleguide.prx.org #161](https://github.com/PRX/styleguide.prx.org/issues/161) via [**ZenHub**](https://www.zenhub.com/)
