### ISSUE TITLE
Cover image well looks like it supports drag-and-drop

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#443]
But it doesn't

**Comment by gcampo88** [comment]
@farski assume you mean this?
![image](https://user-images.githubusercontent.com/16007382/29618410-0f5b41b6-87e6-11e7-93b9-2be89a560b07.png)

if so, applies to Profile and Thumbnail on Series as well:
![image](https://user-images.githubusercontent.com/16007382/29618423-1d27e45c-87e6-11e7-8ff2-e986270be493.png)

**Comment by farski** [comment]
I do mean that

**Comment by gcampo88** [comment]
dup of #265
