### ISSUE TITLE
Problems navigating, especially using back button

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#445]
Jonathan Mitchell  of the truth reporting in conversation that he's had issues in publish with being able to navigate in the publish app, especially when moving back and forth in the app, sometimes requiring a refresh of the page - generally described it as 'buggy'.

We should follow up with him, and maybe see if we can screen share and pin down where he is having issues.

**Comment by kookster** [comment]
@palomao can you follow up with Jonathan sometime and see if you can find out more about what kinds of problems he is seeing in publish?

**Comment by kookster** [comment]
@palomao can we assign this to the current sprint this week (Rosa)?

**Comment by sandikbarr** [comment]
One bug I have definitely seen with the back button is from the N Episodes in Series list (https://publish.staging.prx.tech/series/your-series-id/list) is if you click an episode then use the back button to return to the episodes list, it throws an error. I looked into it, and it appears to be a null check missing from where we subscribe to the TabService model. We get a change to the series Observable but the series.doc is initially null when using the back button. Seems like this a pretty common pattern in our components. Cleaning that up would probably help a lot.

**Comment by sandikbarr** [comment]
Ryan fixed the back button problem I was referencing above with the N Episodes in Series list. 🌮
