### ISSUE TITLE
Ping Feedburner after publish

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#471]
Just to speed things along

**Comment by kookster** [comment]
this actually needs to be done by feeder, not publish, and it does have a
ping capability - though it is throwing errors - so I think this is a dupe
of fixing the ping function in feeder

On Wed, Oct 11, 2017 at 10:40 AM, Chris Kalafarski <notifications@github.com

**Comment by kookster** [comment]
dupe https://github.com/PRX/feeder.prx.org/issues/233
