### ISSUE TITLE
Switch signer host to new deployment

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#484]
`upload-kbp9bfcpj3-us-east-1.prx.tech`

and `upload-kbp9bfcpj3-us-east-1.staging.prx.tech`

**Comment by gcampo88** [comment]
@farski what exactly needs to happen here, just swap these in as `SIGN_URL` in aws-secrets for prod + stag? 

trying both locally: 
- looks like both will need `/signature` appended in order to swap in seamlessly
- `upload-kbp9bfcpj3-us-east-1.staging.prx.tech` doesn't work for me (and I don't see it in Route53...?)
- getting a CORS error when I try to use the prod one locally (though that may be because of the .dev)

**Comment by farski** [comment]
- Looks like it's actually `upload-5e12hsv5dh-us-east-1.staging.prx.tech`
- I'm not sure exactly what needs to get reconfigured. The paths might be slightly different, but the `/signature?to_sign=` part should be the same. The entire new URL for production is `https://upload-kbp9bfcpj3-us-east-1.prx.tech/signature?to_sign=test`, but I'm not sure which parts of that evaporate assumes/dictates. Looking at the old value probably would tell you.
- Not sure about the CORS. I think you had added support for that and put in some tests which are passing in CI I believe

**Comment by farski** [comment]
@pkarman this might be a good small-ish ticket to work on if you're looking for an excuse to get some familiarity with our implementation of `aws-secrets`

**Comment by farski** [comment]
This is [the config](https://console.aws.amazon.com/systems-manager/parameters/%252Fprx%252Ftest%252Fmeta.prx.org%252FUPLOAD_HOST/description?region=us-east-1) used by acceptance tests in Parameter store. It's using the staging deploy of the new/correct publish.prx.org (the one deployed through CD), and it's using the custom `.prx.tech` domain, which is fine for now.

**Comment by farski** [comment]
It's looks like currently secrets for staging and production publish point to the same old version of the upload signing Lambda/API Gateway

`SIGN_URL=https://6fzgppd4bk.execute-api.us-east-1.amazonaws.com/prod/signature`

**Comment by farski** [comment]
So I believe the values that need to go in are:

stag: https://upload-5e12hsv5dh-us-east-1.staging.prx.tech/signature
prod: https://upload-kbp9bfcpj3-us-east-1.prx.tech/signature

**Comment by pkarman** [comment]
@kookster and I tried this in staging, but got CORS error when we tested at publish.staging.prx.tech:

![screen shot 2018-03-01 at 2 09 59 pm](https://user-images.githubusercontent.com/1205061/36867296-590b03f0-1d5a-11e8-8e02-24189ca4962c.png)

**Comment by pkarman** [comment]
@farski I suspect there's some CORS config to be done somewhere to fix this.

**Comment by farski** [comment]
@pkarman https://github.com/PRX/Infrastructure/blob/master/stacks/upload.prx.org.yml#L56 should be a wildcard

**Comment by pkarman** [comment]
@farski - thanks I will PR

**Comment by pkarman** [comment]
@farski the error message mentions `Access-Control-Allow-Origin` and the line you reference in the upload.prx.org.yml is `Access-Control-Allow-Headers`

I don't know enough about how the upload endpoint config works to know if the error message is a red herring or not.

**Comment by farski** [comment]
@pkarman so that config (those three lines) are the headers for the `OPTIONS` request.

`curl -v -X "OPTIONS" "https://upload-5e12hsv5dh-us-east-1.staging.prx.tech/signature?to_sign=test"`

```
< HTTP/2 200 
< content-type: application/json
< content-length: 0
< date: Thu, 01 Mar 2018 21:55:58 GMT
< x-amzn-requestid: 52cec99a-1d9b-11e8-9c61-cd6a5ea731b9
< access-control-allow-origin: *
< access-control-allow-headers: Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token
< access-control-allow-methods: GET,OPTIONS
< x-cache: Miss from cloudfront
< via: 1.1 901034d5d4414b1ff9a2fe4433360a1d.cloudfront.net (CloudFront)
< x-amz-cf-id: sHmhr2x0eRiErPD8Qh_MWaWvmRxMq4m0dihUgFSULnoq2n1b6EfLPQ==
```

The `GET` request is not currently configured to return CORS headers

`curl -v -X "GET" "https://upload-5e12hsv5dh-us-east-1.staging.prx.tech/signature?to_sign=test"`

```
< HTTP/2 200 
< content-type: text/plain
< content-length: 28
< date: Thu, 01 Mar 2018 21:56:28 GMT
< x-amzn-requestid: 64b28f3a-1d9b-11e8-a2d7-a1709d55f835
< x-amzn-trace-id: sampled=0;root=1-5a98770c-eda3a4e519f0da5baf51a514
< x-cache: Miss from cloudfront
< via: 1.1 47d6834f4a1b452aaf7621406b34f3c1.cloudfront.net (CloudFront)
< x-amz-cf-id: JkGB1q5Faa7rehWXKBYseSVo1Uaxvqo6580EGT8VhJ-B_vqKI6aTkw==
```

It looks like we need to add `Access-Control-Allow-Origin` to the `GET` request as well.

That would mean replicating bits of the `UploadRestApiOptionsMethod` resource definition (starting at [L45](https://github.com/PRX/Infrastructure/blob/master/stacks/upload.prx.org.yml#L45)) dealing with the integration response and method response up into the `UploadRestApiSignatureMethod` ([L34](https://github.com/PRX/Infrastructure/blob/master/stacks/upload.prx.org.yml#L34)) resource definition.

The docs for the [AWS::ApiGateway::Method](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html) detail what all those properties are. You may be able to get through that with learning all the ins-and-out of [API Gateway](https://aws.amazon.com/api-gateway/). Or I'm happy to pair on this, because API Gateway, and especially deploying changes, can be a bit temperamental.

**Comment by pkarman** [comment]
@farski I took a shot at it in https://github.com/PRX/Infrastructure/pull/194

**Comment by pkarman** [comment]
after updating the CORS headers in the lambda response itself, this works in staging.

now working on prod.

**Comment by pkarman** [comment]
I was able to upload files to production before and after the config change.
