### ISSUE TITLE
Add podcast feed cap field

### ISSUE THREAD

**Issue by gcampo88** [PRX/publish.prx.org#494]
Feeder can set a `display_episodes_count` to cap the number of episodes that appear in a feed. This isn't requested terribly often, but we could consider adding this to Publish (in Advanced under Podcast Info, most likely) if it becomes more popular. Iceboxing with low priority for now.

**Comment by sandikbarr** [comment]
Feed episode limit was recently added under Series -> Podcast Info -> Advanced Settings. Closing.
