### ISSUE TITLE
Stitched audio preview

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#497]
It would be great if there were some way to preview what the stitched version of a story will be like prior to publishing. Perhaps one version with nothing between the original audio, and another with something (a bit of tone, silence, idk)

**Comment by cavis** [comment]
Doesn't the "Player" tab already do this?  It requests the audio from dovetail with a `?_t=your-auth-token` param, so it can request the unpublished episode files from feeder.

**Comment by farski** [comment]
Ah. I don't think I realized that player actually worked, because as soon as you hit play the UI gets into a real weird state, and I guess I never waiting long enough for the audio to start playing.

**Comment by cavis** [comment]
Yeah, I think it's a bug that the title isn't showing.  When the episode isn't published yet, the player should be manually setting all the fields (title/subtitle/image/etc), rather than pulling them from the rss feed (which doesn't have this episode yet).

**Comment by gcampo88** [comment]
this may be a bug in Play -- it looks like the player still has a class of `loadingRender`. If you take out that class you see the title + subtitle. 
![image](https://user-images.githubusercontent.com/16007382/35172962-b6c6bb44-fd37-11e7-8d02-ccba66a9484d.png)

**Comment by farski** [comment]
How about the missing play button?

![image](https://user-images.githubusercontent.com/3483/35173146-5abc743c-fd38-11e7-8218-88fa6f40dc2e.png)

**Comment by gcampo88** [comment]
huh. maybe? when I was fiddling with this just now only the title + subtitle were missing, not the play button. (have you already added audio to the story?)

**Comment by gcampo88** [comment]
=> https://github.com/PRX/play.prx.org/issues/186

**Comment by farski** [comment]
ya afaik you can only get to that tab once audio has been added

**Comment by pkarman** [comment]
moved to https://github.com/PRX/play.prx.org/issues/186
