### ISSUE TITLE
Affiliate Links

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#521]
<img width="661" alt="screen shot 2018-05-29 at 3 35 39 pm" src="https://user-images.githubusercontent.com/2250413/40684123-2737bf70-6356-11e8-974f-c5dbfb117d1c.png">
Users can add affiliate links to other podcasts with similar content

**Comment by sandikbarr** [comment]
sorry if I am forgetting, did we decide how this works? 😬

**Comment by pkarman** [comment]
@sandikbarr can you score this and move to backlog please?

**Comment by sandikbarr** [comment]
I need grooming done on it @pkarman. @camcavers can we discuss?
