### ISSUE TITLE
Prevent invalid audio files (wav) from being published

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#531]
Had a producer upload a wav file, and get it to publish - that shouldn't happen, should validate it wasn't an mp3.
Once we support transcoding, it's a different story.

**Comment by cavis** [comment]
I did some testing, using their original file.  Normally, Publish doesn't recognize the file, and won't even let you save it: 

![image](https://user-images.githubusercontent.com/1410587/42702002-5c2160b8-8685-11e8-9f0c-7da83ec6363c.png)

I suspect they used some browser that _did_ recognize the wav file as audio (tried Chrome/FF/Safari, and none of them let me click save).  And after you click save, we have nothing else in the cms-audio-lambda -> CMS-callback-worker chain to invalidate the audio_file.  Though I thought even there we had content-type checks.

**Comment by cavis** [comment]
Oh wait ... I think this is a problem in their [1 segment audio file template](https://cms.prx.org/api/v1/audio_version_templates/288)

It has a `nil` content-type (not even showing up in that representer).  So Publish/CMS don't validate the content type at all.  I wonder how that happened?

**Comment by cavis** [comment]
Nothing to do!
