### ISSUE TITLE
No where to see complete pubDate

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#533]
Because of limitations with the date picker for Release Date, we set some release dates manually through the console to offset some episodes by a few seconds. 

![image](https://user-images.githubusercontent.com/3483/43629417-322352c0-96cb-11e8-9c30-aed8f74628ab.png)

In the UI currently when the pubDate is displayed it drops the seconds, so nowhere accurately reflects the pubDate

![image](https://user-images.githubusercontent.com/3483/43629472-5979b486-96cb-11e8-900d-4847a1b00f11.png)
![image](https://user-images.githubusercontent.com/3483/43629484-6030285a-96cb-11e8-8da5-f21f63aa9a0d.png)

**Comment by sandikbarr** [comment]
Should be resolved with #605 and https://github.com/PRX/styleguide.prx.org/issues/131
