### ISSUE TITLE
Errors on save

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#534]
I ended up manually publishing (rather than scheduling) five of episodes because of [issues](https://github.com/PRX/styleguide.prx.org/issues/61) [with](https://github.com/PRX/publish.prx.org/issues/532) [setting](https://github.com/PRX/publish.prx.org/issues/533) the pubDate, so I queued the changes (just altering the release dates) up in five tabs to save as-fast-as-possible, and once I did that (probably took ~2s) 2/5 of the saves errored on the first attempt. It took me long enough to realize that that had happened (< a minute), that there was a period where the public feed was missing episodes:

![screen shot 2018-08-03 at 3 02 02 am](https://user-images.githubusercontent.com/3483/43629958-cd7ce73a-96cc-11e8-9e8b-3649a1a58b5b.png)
_(missing `#3` and `#5`)_

Had to scramble to to get the episodes resaved and ping FB to make sure nothing picked up the feed in the bad state.

40% error rate feels high just for getting episodes to publish.

**Comment by kookster** [comment]
Deadlock - 

Error raised by Api::Auth::StoriesController#update:
Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction

URL: /api/v1/authorization/stories/250469
Time: Aug  3, '18  2:58 am

To see the error, click this link:
https://rpm.newrelic.com/accounts/43935/applications/61249332/traced_errors/98969119-96ea-11e8-8ec6-0242ac110008_0_5904

**Comment by cavis** [comment]
Fixed!  Forever!
