### ISSUE TITLE
Add an 'adfree' checkbox

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#574]
Currently an `adfree` tag is added by adding a freeform tag to the Categories field. We will need to extrapolate this out and provide it as a checkbox option.

**Comment by cavis** [comment]
FYI the tag is `"adfree"`, and shows up as:

- `Categories` on the main story-edit page in Publish (_A comma-separated list of tags relevant to the content of your episode._)
- On the [CMS story](https://cms.prx.org/api/v1/stories/266484) as `"tags": ["adfree"]`
- On the [Feeder episode](https://feeder.prx.org/api/v1/episodes/b4786825-211f-40b2-a52d-3e96e48dbbfc) as `"categories": ["adfree"]`

May be able to do something as simple as linking the new checkbox to the `tags` textfield on the frontend.  So when you update one it changes the other.

**Comment by cavis** [comment]
Per team conversation: there may be a case for a CMS/Feeder schema change here.  It's a bit wonky to have `"adfree"` showing up in our feed xml.

Crazy ideas to consider:

- Some sort of "internal tags" field in CMS
- An adfree boolean in CMS
- An adfree boolean in Feeder
- ???

**Comment by cavis** [comment]
I guess I'm still of the opinion we should just add a checkbox that manipulates the `Categories` in Publish.  And open up another ticket to consider an actual schema change (which also requires a Dovetail/Adzerk change).

Or maybe we just blacklist the tag in Feeder, so it doesn't show up in the XML but does show up in the episode JSON there.

**Comment by brandonhundt** [comment]
I'm also of the same opinion as @cavis:

> we should just add a checkbox that manipulates the `Categories` in Publish. 

I will create a separate ticket for the schema changes
