### ISSUE TITLE
Add Episode Notes field

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#575]
Textarea for producers to signal to sponsorship some non-user facing notes that may affect ad sales (eg ‘this episode contains content about suicide’)

It would not surface in feeds. Only in some Publish only displays like the Production Calendar.

Comment from Ryan:
> Note: this may land on either the "story", or the "podcast distribution". Depending on whether we deem it podcast-specific info.

**Comment by cavis** [comment]
Not sure we have any suitable field on the Story currently.  So would have to add something.

We do have a `properties` field on the distribution which is just a json blob of whatever data you want.  So if we deem this "podcast specific" ... we could store it there.

But I'm starting to think the production-calendar is _not_ podcast specific.

**Comment by kookster** [comment]
We do have some exchange fields for production related info, might be appropriate? worth checking, but happy to add a new one!

**Comment by brandonhundt** [comment]
Needs a CMS ticket. @pstjean will create the ticket.
