### ISSUE TITLE
Adjust time of day in the schedule picker field

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#576]
- The time of day is should remain hidden, unless the state is changed to Scheduled, then it should be shown. 
- The time of day should allow of any hour or minute to be selected. (currently limited to every halfhour)

**Comment by cavis** [comment]
Just for background: producers sometimes want to drop many episodes "all at once".  And the way to maintain the correct ordering in the feed is to get the published dates all set 1-second apart.

**Comment by sandikbarr** [comment]
@brandonhundt This ticket no longer seems valid. Can you verify?
We should allow users to set time of day in all states, Draft, Scheduled, Published.
Also as much as possible, we need to preserve the release date when published states are toggled: https://github.com/PRX/cms.prx.org/issues/501
