### ISSUE TITLE
Rearrange episode creation fields to reflect new workflow

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#577]
In order to accommodate creating drafts more quickly for the production calendar, we should rearrange the field order on episode pages. 

More info on fields here in the doc provided. This just determines order of fields on the page: https://docs.google.com/document/d/1PcMEXupse9kFDxBbitMeODBv1_GvIQeQWE0kve2z7A4/edit#

**Basic Info**
- Title
- Publish date scheduler
- Audio Files (audio template selection)
- Ad-Free checkbox
- Season and Episode Numbers
- Episode Notes

**Metadata**
- Clean Title
- Teaser
- Description
- Cover Image
- Categories
- Explicit
- Episode Type
- Author Information
- Episode URL
- Itunes Summary

**Comment by kookster** [comment]
Also be sure to notify @palomao of changes, as this impacts producer workflow (hopefully in a good way)

**Comment by brandonhundt** [comment]
After discussing with @cavis and @sandikbarr, I'm going to close this ticket without development. 

The reason is that I was unaware of existing contextual changes that occur to tabs based on the series.
