### ISSUE TITLE
User toggle between Scheduled and Publish states with validated fields

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#579]
In the Publish widget (err box), we need to allow the user to toggle between states, if field validation passes. 

If not able to do so already, user should be able to create drafts without passing all validation.

**Comment by kookster** [comment]
Let's have a larger discussion about publishing and scheduling and clean up the states, communication to users, and prod calendar scheduling.

**Comment by kookster** [comment]
Also look at @svevang 'c code in publish series model for how validations can be handled

**Comment by brandonhundt** [comment]
View the prototype to see the changes as outlined in #594. May need to revisit the estimate.

- Prototype link: https://hidden-wildflower-4555.animaapp.io/draftnotsaved
- Prototype Notes Doc: https://docs.google.com/document/d/1nvgyuGeOkR47Pmt3D_iCmgSWgNRv-_pkRdzTIok3OU4/edit
