### ISSUE TITLE
Implement homepage layout changes as noted in protoype

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#582]
![publish homepage](https://user-images.githubusercontent.com/369739/52304043-50713200-2957-11e9-907b-3b7f6a04df20.png)

The changes represented in this prototype are intended for producers, allowing them to easily access existing content. This way producers are reminded to update their existing drafts instead of creating new episodes that may already be in the system. 

Like now, one series is listed at a time, with the 10 most recent items showing in descending order.

**Comment by cavis** [comment]
Are episode-thumbnail images not useful?  Not all shows change (or even upload) images from episode to episode.  But some do (Song Exploder, Allusionist, Mortified).

**Comment by kookster** [comment]
n.b. estimate may be low ;)

**Comment by sandikbarr** [comment]
implemented in #614
