### ISSUE TITLE
ICS calendar export of production calendar view. (Subscribe to a calendar)

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#586]
Also a candidate for Courier

**Comment by kookster** [comment]
I think that is ical format, with .ics file extension to make outlook happy as per @rpeterman-gp

**Comment by kookster** [comment]
similar approach to csv

**Comment by brandonhundt** [comment]
From @kookster: 

> also, regarding csv export, or ical, I was thinking it might be worth asking users if they want to have a cal they can subscribe to, like add to google calendar

> I believe the thing to implement for that is webcal links that return ical
and this looks like a decent example in rails https://www.toasterlovin.com/rails-webcal-links-with-icalendar-gem/

> the other standard is caldav, which like webdav, gives editing/authoring options, which I don't think we need
