### ISSUE TITLE
Sticky toolbar in edit screens covers application link dropdown.

### ISSUE THREAD

**Issue by rpeterman-gp** [PRX/publish.prx.org#588]
### Reproduce
- Edit any episode.
- Scroll page till header becomes fixed positioned.
- Hover over your account pic to reveal application links.
- Note that the dropdown is covered up by the header.

### Cause
Though the `.nav-userinfo-menu-apps[_ngcontent-c3]` element has a z-index of 999, it has ancestors that are positioned, localizing that depth to within their scope. Ultimately it is the `<prx-header>` element's z-index that will be responsible for sorting its depth to be above anything else contained in its top level siblings. Right now it shares the same z-index as the sticky toolbar, 200. Since the toolbar doesn't have any positioned ancestors, its z-index scope is the same as the header, which cause source order to place it on top of the header.

### Proposed Solution
Change the z-index of the `<pri-header>` element to 201 or higher.

**Comment by kookster** [comment]
might be a style guide change, but should also be controlled at the app level as a layout issue

**Comment by rpeterman-gp** [comment]
Closing here in favor of fixing in PRX/styleguide.prx.org#125.
