### ISSUE TITLE
Revisit UX for publishing states

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#594]
Ideas:
* Release date included in publish box
* Clearer state names in button.
* Save/Delete button repositioning. (??)
* Alert boxes for unpublishing (You can make changes without unpublishing the post)

Other ideas TBD.

**Comment by brandonhundt** [comment]
**Prototype:** https://hidden-wildflower-4555.animaapp.io/draftnotsaved

**Prototype notes:** https://docs.google.com/document/d/1nvgyuGeOkR47Pmt3D_iCmgSWgNRv-_pkRdzTIok3OU4/edit#

Protot

**Comment by sandikbarr** [comment]
Thanks for the demo this morning! Things are feeling so much better. Can't wait to close out some old tickets related to some of this: https://github.com/PRX/publish.prx.org/issues/354 https://github.com/PRX/styleguide.prx.org/issues/63 https://github.com/PRX/styleguide.prx.org/issues/61
