### ISSUE TITLE
Browser mp3 validation with id3 image

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#595]
Have had a few user reports where they upload an mp3 to Publish, and get a "not an mp3 file" validation error.  This specific error message comes out of browser-side file type detection.

@sandikbarr has confirmed that this happens in Safari, when there's an id3 image in the file.  Difference might be that Chrome can use aurora-js validation, and Safari falls back to native html audio.

May also occur in Firefox.

**Comment by sandikbarr** [comment]
That specific `file.format` of the mp3 with the embedded image is registering as "mpeg" in both Safari and Firefox. Other mp3s I tried with and without cover images have `file.format` "mp3" so not sure what it is about that specific file.
* One fix would be to allow "mpeg" and "mp3" through here https://github.com/PRX/publish.prx.org/blob/master/src/app/shared/model/invalid/audio.invalid.ts#L78
* Or we could just get rid of that check altogether and as you said it will get caught in processing and prevent publishing the episode

**Comment by cavis** [comment]
Hmm... it would be nice to ditch Aurora and _most_ of those client-side validations.  Assuming the CMS/lambda validation goes decently fast.

But for now, I think the allow-mpeg-or-mp3 would be sufficient.  And maybe open a new ticket for "ditch aurora"?
