### ISSUE TITLE
per series Dashboard

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#608]
![publish homepage](https://user-images.githubusercontent.com/2250413/53820054-b4741f80-3f30-11e9-8be4-930f96de6522.png)
Per series dashboard view
* [x] lays stories out in a vertical list default ordered by publishedAt || lastUpdated
* [x] removes the episode images
* [ ] Has a link to the episode metrics (requires getting the podcast audio version for the guid) (support needed in metrics to enable direct linking to an episode guid)
* [ ] Allows filtering by publish state (needs support in CMS)
* [x] ~Allows episodes to be sorted by _____?~
* [x] New episode buttons move to each series header

**Comment by brandonhundt** [comment]
@sandikbarr Updated Prototype here: https://dawn-flower-2080.animaapp.io/publishhomepage
