### ISSUE TITLE
Ad-ops email notification requirements gathering

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#617]
Quick design/requirements gathering on the email alerts that get sent to Ad-Ops. What needs to be in them, etc. They don't need to be really good looking as they are internal and possibly temporary.

**Comment by brandonhundt** [comment]
send emails to: `ad-ops@prx.org`

@cavis suggests: “let’s use our SNS/Announce setup to message this to Courier”

**Comment by brandonhundt** [comment]
**Scenario 1:**
Ad Ops wants to know when the drop date for an episode draft changes with two weeks of the scheduled date.

**EMAIL:**
```Subject: Episode date change within two weeks of dropdate

Body: {{Series Name}} changed the dropdate of {{title}} from {{old_date}} to {{new_date}}.  View it here {{link to episode}}```

Tech note: According to [this thread](https://prx.slack.com/archives/GCEJE5136/p1553527148087300), we may need to extend the `story_updated` event with attributes changes in CMS.

**Comment by brandonhundt** [comment]
**Scenario 2:**
Ad Ops wants to know when an episode draft is deleted within a week of the episode drop date.

**EMAIL:**
```
Subject: Episode deleted within a week of dropdate

Body: {{Series Name}} deleted the episode: {{title}}, which had a dropdate of {{date}}.
```

**Comment by brandonhundt** [comment]
@IcusFMagni This should be ready to break down into smaller tickets maybe converting #581 into an epic to track all the changes.

**Comment by cavis** [comment]
Yeah, and just to +1 some updates to [AnnounceActions](https://github.com/PRX/cms.prx.org/blob/master/app/controllers/concerns/announce_actions.rb) should make it possible to broadcast what activerecord changes occurred.

**Comment by brandonhundt** [comment]
Thanks @cavis!

@IcusFMagni: We should break this down into some implementation tickets. I'll move to done but not closed until then.

**Comment by pstjean** [comment]
This looks great. We've got some well-defined requirements from Ad-Ops, and I definitely agree this is ready to move into ticketing. It looks like we may even have a pretty solid path forward on the technical side.
