### ISSUE TITLE
series performance

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#624]
* Should get feeder ids from url
100+s of requests of the new home page to feeder just to get the podcast and feeder ids. Instead of following the distribution links, "hack" the id from the url so it doesn't have to make all those requests.
* Don't default loadRelated on the series
https://github.com/PRX/publish.prx.org/blob/master/src/app/dashboard/dashboard.component.ts#L47
Those should maybe have a 3rd param of `false` (loadRelated defaults to `true`)
The home page needs the distributions but not the audio templates.
* Don't load the series account
you can just pass `null` as the first parameter

**Comment by cavis** [comment]
Per the "feeder ids from distribution url" ... I can see 2 ways to do that:

1. Be specific - add the logic to the DistributionModel and StoryDistributionModel
2. Be generic - add it to HalDoc in styleguide.  Some sort of a `doc.guessIdFromLink(linkName)`
