### ISSUE TITLE
heading font weights

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#625]
In the title field, can we bold the h2? and not bold the h3?

Example:
```
h2[_ngcontent-c11] {font-weight:bold;}

h3[_ngcontent-c11] {font-weight: normal;}
```

**Comment by sandikbarr** [comment]
heading font weights are set in global CSS, look into what else is using h2 and h3 that would be affected by this

**Comment by brandonhundt** [comment]
I am okay making a global change so all headers have a font-weight of bold.

I tested it out in the Chrome inspector a little, and I like the extra emphasis boldness provides.

**Comment by sandikbarr** [comment]
tech debt
