### ISSUE TITLE
Allow users to add audio segment labels and descriptions

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#656]
Part of The World's workflow on publishing audio segments is adding a unique title and description for each of the segments. We will need to allow this capability once CMS contains the description value.

**Comment by cavis** [comment]
@brandonhundt to provide some design input on adding those fields to the somewhat limited real-estate of the uploader.

**Comment by brandonhundt** [comment]
Initial idea for creating a little more space.

![Screen Shot 2019-07-02 at 1 05 57 PM](https://user-images.githubusercontent.com/369739/60537016-25ec9080-9ccd-11e9-9dd4-8e2efa9d4829.png)
