### ISSUE TITLE
remove hero and use new status bar

### ISSUE THREAD

**Issue by sandikbarr** [PRX/publish.prx.org#658]
Episode:
![Episode - Published](https://user-images.githubusercontent.com/2250413/59231744-70d02800-8ba7-11e9-9b83-673fc046cbf6.png)

Series:
![Series](https://user-images.githubusercontent.com/2250413/59231749-788fcc80-8ba7-11e9-8bec-73475ed47896.png)

A hero looking header image also appears on the new Production Calendar, TBD.

**Comment by rpeterman-gp** [comment]
@brandonhundt Do we want to update the series status bar and side bar to have feedback and action buttons in the same locations as the episode editor? If so, can we move the "Episodes in Series" link to be a tab in the menu, ("Episodes (23)" for the label)?
