### ISSUE TITLE
Odd button positioning on Edit page

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#670]
While looking at the [Edit Series](https://publish.prx.org/series/38796/podcast) page, once a change has been made the buttons are stacked 
![image](https://user-images.githubusercontent.com/3483/62129765-81e30e80-b2a5-11e9-9245-c1da72db6cad.png)

and once you scroll and the toolbar locks to the top, the buttons overflow

![image](https://user-images.githubusercontent.com/3483/62129783-8e676700-b2a5-11e9-92de-1e42edcd1f7a.png)

**Comment by sandikbarr** [comment]
Noting here that #658 was supposed to move the series page to the new toolbar, but only the episode page was done. Instead of fixing the old toolbar and buttons, series should be moved to the new one.

**Comment by brandonhundt** [comment]
Thanks @farski and @sandikbarr I'm going to close this in favor of #658. I've moved #658 to be in the next sprint, it was still in Jagmeet as I'd like to see this fixed.
