### ISSUE TITLE
Evaluate changes needed for an alexa flash briefing and "news on Google Assistant"

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#684]
Audio spec, metadata spec, loudness

**Comment by pstjean** [comment]
We have a flash briefing tested and working for Alexa.

Google's has two distinct beta specifications for this ([Audio News](https://developers.google.com/news/assistant/audio-news/overview#technical-specs) and [News Briefings](https://developers.google.com/news/assistant/newsbriefings/technical-requirements#requirements)), and they've indicated in conversation with The World that they'd like us to support both. They both share one requirement that Publish doesn't support: the image for the feed must be specified as follows:

```
<image>
  <url>http://www.example.com/theexampletimes/logo.png</url>
  <title>The Example Times</title>
  <link http://www.example.com/theexampletimes>
</image>
```

Additionally, they indicate that they only support RFC 822 format for time (i.e. Thu, 22 Sep 2016 21:11:46 GMT) but the current feed published by The World for this service (https://www.pri.org/feed/segmentsworldextra) uses numerical representation for the timezone without issue, so I'm inclined to leave that as is.

**Comment by kookster** [comment]
feeder has image tags for the feed; is the issue that it includes the height and width?
Example from 99pi feed (http://f.prxu.org/96/feed-rss.xml):
```
    <image>
      <url>https://f.prxu.org/96/images/a52a20dd-7b8e-46be-86a0-dda86b0953fc/99-300.png</url>
      <title>99% Invisible</title>
      <link>http://99percentinvisible.org</link>
      <width>1400</width>
      <height>1400</height>
    </image>
```

**Comment by kookster** [comment]
I see the `<link ... >` tag is different in your example, but I thought that might be a typo as it isn't valid looking xml.

**Comment by kookster** [comment]
The example in the News Briefing spec, linked above, does look right:
```
<image>
  <url>http://www.example.com/theexampletimes/logo.png?s=1400</url>
  <title>The Example Times</title>
  <link>http://www.example.com/theexampletimes</link>
</image>
```

**Comment by pstjean** [comment]
Oh, ok great! I was looking at the Passenger List feed (figuring a recent feed would be the best example), which doesn't have that tag. We should be all set, then.

**Comment by kookster** [comment]
It's actually invalid RSS for that channel <image /> tag to be 1400x1400 as specified in the spec.
http://www.rssboard.org/rss-draft-1#element-channel-image-height
