### ISSUE TITLE
Guard against unpublish on stale state

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#698]
Had an issue where a user may have accidentally unpublished from a stale browser window.  Unclear exactly how that may have happened, but for due diligence we should:

- [x] Refactor the story [StatusControlComponent](https://github.com/PRX/publish.prx.org/blob/master/src/app/story/directives/status-control.component.ts#L284) to guard against a stale state.  (Specifically, the `togglePublish` method and anything calling it)

**Comment by cavis** [comment]
Per @svevang this can be reproduced.  Open 2 browser windows, publish in one, save a change in the other.

Should be able to guard against this specific case by disallowing PUT-ing the `published_at` field or changing it indirectly via the `released_at` (either in CMS or Publish or both).  Publish/Unpublish must always be done via those POST endpoints.

**Comment by cavis** [comment]
Hmm.. i've been unable to make this happen.  Tried various combinations of windows open, and scheduling-vs-publishing.  @svevang if you have details can you add them here?

**Comment by svevang** [comment]
Basically, you:

1) open a tab (T1) with a draft story.
2) open another tab (T2) with the same draft story
3) in T2, hit the publish now button, see the published state
4) back in T1, see the draft status, change the title and hit save
5) In T2, hit reload and see that the story is in draft status again.

Here's a video of the reproduction flow:
[multiple - tabs - publish.mov.zip](https://github.com/PRX/publish.prx.org/files/3952816/multiple.-.tabs.-.publish.mov.zip)

**Comment by cavis** [comment]
Ahhhh, okay.  I see what's happening.

When you schedule the episode, you end up with `published_at == released_at`.

When you "publish now" the episode, you end up with `published_at < released_at`.

Then when you update it in the non-refreshed tab, it's going to `PUT` the released_at again (but not the published_at, because it doesn't have that data yet).

Which triggers [this bit of code](https://github.com/PRX/cms.prx.org/blob/master/app/models/story.rb#L351) in CMS, setting `published_at == released_at` again.

(Will have to think about the best way to solve this)

**Comment by svevang** [comment]
My first thought was to use a nonce + rails validation -- preventing the save if the nonce is mismatched and the published state is going to change. A little later I saw the 'optimistic locking' builtin feature in rails, which sorta does that same thing. I wonder if that could be used + a validation to opportunistically lock the publish state?

Per the T1/T2 scenario, I could imagine a user story like:
T1: User hits save, and a warning message appears "It seems you're editing this in another tab".

**Comment by cavis** [comment]
So that `update_published_to_released` CMS method describes 2 use cases:

1. Canceling a scheduled episode (published_at > now, and i want to set it to null)
2. Updating the published_at date on a published episode (published_at <= now, and i want to change it probably for episode sorting purposes)

This feels like an abuse of (2).  The only entry points into "publishing/unpublishing" an episode should be the controller/[model](https://github.com/PRX/cms.prx.org/blob/master/app/models/story.rb#L289) explicit calls.  So we could just narrowly guard against "released_at > now" in `update_published_to_released`.  And return a validation error or something.

**Comment by cavis** [comment]
This appears to still be a problem.  Just saw a user somehow unpublish an episode, mixed in with a dashboard load I think.  Cloudwatch logs for that IP:

**CloudWatch Logs Insights**  
region: us-east-1  
log-group-names: infrastructure-cd-root-production-ContainerAppsRootStack-1CE4WTB9SCMHG-CmsStack-O4E883E41R0V-WebLogGroup-ABGWNTKY21GR  
start-time: 2020-09-22T21:10:56.000Z  
end-time: 2020-09-22T21:18:03.000Z  
query-string:
```
fields @message
| filter @message =~ "2601:644:400:d1c0:151b:8884:11b4:33dc"
| sort @timestamp asc
```

----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                                                                                                         @message                                                                                                         |
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Started GET "/api/v1" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:42 +0000                                                                                                                             |
| Started OPTIONS "/api/v1/authorization" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:42 +0000                                                                                                           |
| Started GET "/api/v1/authorization" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:42 +0000                                                                                                               |
| Started GET "/api/v1/authorization" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000                                                                                                               |
| Started OPTIONS "/api/v1/authorization/stories/338906" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000                                                                                            |
| Started PUT "/api/v1/authorization/stories/338906" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000                                                                                                |
| Started GET "/api/v1/users/551" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000                                                                                                                   |
| Started OPTIONS "/api/v1/authorization/series?zoom=prx%3Aimage&filters=v4" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000                                                                        |
| Started GET "/api/v1/authorization/series?zoom=prx%3Aimage&filters=v4" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000                                                                            |
| Started OPTIONS "/api/v1/authorization/series/37983/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000 |
| Started OPTIONS "/api/v1/authorization/series/37783/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000 |
| Started OPTIONS "/api/v1/authorization/series/38517/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000 |
| Started OPTIONS "/api/v1/authorization/stories?page=1&per=10&zoom=false&filters=noseries%2Cv4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000   |
| Started OPTIONS "/api/v1/authorization/series/37983/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:43 +0000 |
| Started GET "/api/v1/authorization/series/37983/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000     |
| Started OPTIONS "/api/v1/authorization/stories?filters=noseries%2Cv4" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000                                                                             |
| Started OPTIONS "/api/v1/authorization/series/38517/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000 |
| Started OPTIONS "/api/v1/authorization/series/37783/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000 |
| Started OPTIONS "/api/v1/authorization/stories?page=1&per=10&zoom=false&filters=noseries%2Cv4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000   |
| Started GET "/api/v1/authorization/series/37783/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000     |
| Started GET "/api/v1/authorization/stories?page=1&per=10&zoom=false&filters=noseries%2Cv4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000       |
| Started GET "/api/v1/authorization/series/38517/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dunpublished&sorts=released_at%3A%20asc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000     |
| Started GET "/api/v1/authorization/series/37983/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000     |
| Started GET "/api/v1/authorization/stories?filters=noseries%2Cv4" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000                                                                                 |
| Started GET "/api/v1/authorization/series/38517/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000     |
| Started GET "/api/v1/authorization/series/37783/stories?page=1&per=10&zoom=false&filters=v4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000     |
| Started GET "/api/v1/authorization/stories?page=1&per=10&zoom=false&filters=noseries%2Cv4%2Cstate%3Dpublished&sorts=published_at%3A%20desc" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000       |
| Started OPTIONS "/api/v1/authorization/stories/338906/unpublish" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000                                                                                  |
| Started POST "/api/v1/authorization/stories/338906/unpublish" for 2601:644:400:d1c0:151b:8884:11b4:33dc at 2020-09-22 21:16:44 +0000                                                                                     |
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
