### ISSUE TITLE
Add keyword list to cards in the calendar list view

### ISSUE THREAD

**Issue by brandonhundt** [PRX/publish.prx.org#731]
Underneath the title, we should add a comma separated list of keywords (tags) on the episode.

![Screen Shot 2020-10-26 at 9.56.40 AM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/6e5a8d2b-86d2-4b9c-8e94-f952712fe40d)

**Comment by cavis** [comment]
The ask is mainly to get "adfree" episodes.  And we'll cover that in the basic Augury "100x requests" backsaw for now.  (Augury already has the entire episode schedule and keywords).
