### ISSUE TITLE
iTunes episode type required, but not validated or defaulted in publish when saving a new episode

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#734]
Reproduce - 
1. Create a new episode, set title, teaser, description
2. Click on podcast info, set author name and email
3. Hit Save

You'll get a box pop up with a 500 saving a PUT to feeder episode update, with this exception:
`ActiveRecord::RecordInvalid: Validation failed: ITunes type is not included in the list`

**Comment by cavis** [comment]
Add the `REQUIRED()` validator to the model.
