### ISSUE TITLE
Add series name to scheduled episode titles?

### ISSUE THREAD

**Issue by farski** [PRX/publish.prx.org#744]
Might make it easier to know what you're looking at when you have many shows with planned episode.

**Comment by brandonhundt** [comment]
Original Slack Thread: https://prx.slack.com/archives/CG7G1FPNJ/p1615558808018300

**Comment by brandonhundt** [comment]
Ideas off the top of my head:

**1. Scope limit Publish to view only 1 show at a time, ala Metrics.** 
Pros: 
- Makes it easier to find the show you want to view than scrolling through the long list or going to the Series Search tab. 
Cons: 
- We may allow multiple shows to be selected in Metrics, leading to some inconsistency, but it may not matter as the behavior is similar.
- A LOT OF WORK.  

**2. Add series logo to the Status Bar in the Plan Episodes screen** (Its not present r/n)
Pros: Light lift
Cons: Will it be noticed anyway???

![Screen Shot 2021-03-23 at 11.34.36 AM.png](https://images.zenhubusercontent.com/5bd1dc3a4cadef67d2695e38/b0ebc5c6-bfd8-4836-b758-dfb53d7c23a1)

**Comment by brandonhundt** [comment]
As I think about this ticket, I realize my last comment takes this too far!!!!

Per simply adding the series title to episode, I'm open to it, but it's not something we need to act on quickly.

**Comment by brandonhundt** [comment]
Closed in favor of #746
