### ISSUE TITLE
Add payment pointer to the UI

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#766]
Set the payment pointers for use in web monetization, that were added in feeder: https://github.com/PRX/feeder.prx.org/pull/429

**Comment by brandonhundt** [comment]
Here's the design: https://www.figma.com/file/JX0HPXGk5xt8s1NWZBXjgT/PRX-Play?node-id=70%3A4252

At this moment only Coil provides micropayments. So the only thing we need to capture in Publish is the URL provided by Coil.

We will need to establish this tab, so fields can be provided in the future too.
