### ISSUE TITLE
Provide a specific podcast > item > guid?

### ISSUE THREAD

**Issue by kookster** [PRX/publish.prx.org#78]
Normally we generate these based on the story id or generated, but we need a way to be able to specify them, esp. for when we are importing an existing feed.
This override is available in feeder now, need to think about how we want to get that in there for series imported into the publish platform - even if this is set by a script, user may need to be able to see and update the override guid.

**Comment by kookster** [comment]
Do this by posting the guid to feeder directly, this won't be saved in cms

**Comment by cavis** [comment]
@kookster if these guids are already writeable in feeder ... is there a ticket to add them to the Publish UI?  (I thought that was what this ticket was for).

**Comment by kookster** [comment]
I thought we had a more generic "add a tab to update feed episode related fields" ticket for a story, but if not I'll add it - I know we have one for series/feeds.
