### ISSUE TITLE
Incorporate embed player

### ISSUE THREAD

**Issue by cavis** [PRX/publish.prx.org#91]
Add the embed player to the story-embed tab.  Pre-fill all fields, show a preview, and just give the user a copyable link to use.

Bonus points: allow user to alter some aspects of the player - but don't save changes to CMS or anything crazy.  Just change the copyable link.

**Comment by gcampo88** [comment]
Working on this; one question for @cavis / anyone: I can pull the title out of the StoryModel object, but currently there's no way to get the audio url with ads, etc, correct? Is that something that will be doable soon? I'm wondering if I should flash a message to the user that they need to save their Story before they can see the player preview, since it'll rely on the feed URL, image URL, audio URL etc which will only be set up stably once they hit Save, right? Holler if I'm way off base...

**Comment by cavis** [comment]
You're right - CMS currently doesn't know anything about the destination podcast feed.  (This is related to what @kookster is currently working on).  You're also not guaranteed to have a single mp3 file - it may be multiple files at this point.

I'm inclined to say "fake it" for what you're missing, as we're most interested in feedback over functionality.  Meaning ... plug in the CMS-returned values for the image and first-audio-file, and leave the subscription-url blank.  (Unless the player already supports multiple file inputs?)

**Comment by cavis** [comment]
Also, sticking with the UX themes of Publish ... maybe the embed player you show on the page (the "preview") doesn't need to be the link you give them to copy.  Meaning, you always want them to copy a URL using the currently-live feed, but you want to show them what pending changes "would look like eventually" after they click save.

**Comment by gcampo88** [comment]
not sure what you mean with the "currently-live feed" -- if this is a new story there's no live feed at the moment, right? Or do you just mean the first audio file?

**Comment by cavis** [comment]
So eventually, CMS will be able to tell for any story whether it has an RSS feed distribution, and what the URL to that is.  If it exists, make sure the copyable-player-link you give them is for the public feed, which could be out-of-sync with the data CMS has.

But the preview of the player you should them should pull from CMS (or maybe even unsaved localstorage changes), with the latest data.

And if the story doesn't have an RSS feed ... well, that's another good question.  We could give them a non-podcast-audio player, that just links to the CMS audio files stored in S3.  Or we can just not give them anything, and say only podcasts get the player.
